services:
  postgres:
    container_name: postgresql_wb
    image: postgres:latest
    restart: "always"
    environment:
      POSTGRES_DB: "wb0"
      POSTGRES_USER: "oswyndel"
      POSTGRES_PASSWORD: "wb_2024"
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
  nats:
    container_name: nats-wb0
    image: nats
    restart: "always"
    ports:
      - 4222:4222
      - 8222:8222
    command: ["-js", "--server_name", "test", "--http_port", "8222"]
    
  
