services:
  postgres:
    image: postgres:latest
    restart: "always"
    environment:
      POSTGRES_DB: "wb0"
      POSTGRES_USER: "oswyndel"
      POSTGRES_PASSWORD: "wb_2024"
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    
  
